type: reference-docs
definitionId: configuration
label: Configuration
settings:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Java
      - lang: Python
  showConsole: false
  hideHostname: true
  hideDownloadButton: true
  # downloadDefinitionUrl: https://doc.toasttab.com/api-specifications/toast-config-api.yaml
