openapi: 3.1.0
info:
  title: Seller to Fast API
  version: V1
  license:
    name: Fast Developer Terms
    url: "https://www.fast.co/terms/developer-terms"
  contact:
    name: Fast
    url: "https://fast.co"
    email: api@fast.co
  description: |-
    # Authentication

    <!-- ReDoc-Inject: <security-definitions> -->
tags:
  - name: Seller to Fast API
    description: Seller to Fast API
paths:
  "/v1/external/orders/{order_id.value}":
    $ref: "paths/v1@external@orders@{order_id.value}.yaml"
  "/v1/external/orders/{order_id.value}/business_event":
    $ref: "paths/v1@external@orders@{order_id.value}@business_event.yaml"
  "/v1/external/orders/{order_id.value}/refund":
    $ref: "paths/v1@external@orders@{order_id.value}@refund.yaml"
servers:
  - url: https://api.fast.co
    description: Production server (for live site)
  - url: https://api.sandbox.fast.co
    description: Sandbox server (for testing)
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: FASTSESSION
      in: header
