openapi: 3.0.0
info:
  title: Fast to Seller API
  version: v1
  contact:
    name: Fast
    url: 'https://fast.co'
    email: api@fast.co
  description: |-
    # Authentication

    <!-- ReDoc-Inject: <security-definitions> -->
tags:
  - name: Fast to Seller API
    description: Fast will communicate with your server application on these endpoints.
paths:
  /fast/v1/create:
    $ref: paths/fast@v1@create.yaml
  /fast/v1/read:
    $ref: paths/fast@v1@read.yaml
  /fast/v1/update:
    $ref: paths/fast@v1@update.yaml
  /fast/v1/delete:
    $ref: paths/fast@v1@delete.yaml
servers:
  - url: 'https://private-api.fast.co'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: FASTSESSION
      in: header
